Resources:
  FraudDetectionLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: FraudDetectionFunction
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      Code:
        S3Bucket: your-s3-bucket-name
        S3Key: your-lambda-code.zip
      MemorySize: 128
      Timeout: 30
